#!/bin/bash

set -ex

pip install -r requirements_postbuild.txt

cd sentiment_analysis
curl https://transfer.sh/1e3o7EO/cc.de.100.gensim_model.tar.gz -o cc.de.100.gensim_model.tar.gz
tar -zxf cc.de.100.gensim_model.tar.gz
rm -rf cc.de.100.gensim_model.tar.gz
